# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    allowed_methods_listener:  true
    view:
        view_response_listener:  true
    format_listener:
        rules:
            - { path: ^/v1, prefer_extension: true, fallback_format: json, priorities: [ json ] }
            - { path: ^/, prefer_extension: false }

